#
#server:
#port: 8086
#
#spring:
#application:
#name: performance-service
#datasource:
#url: jdbc:mysql://localhost:3306/performance_service
#username: hbstudent
#password: hbstudent
#
#jpa:
#properties:
#dialect: org.hibernate.dialect.MySQLDialect
#hibernate:
#ddl-auto: update
#show-sql: true
#
#eureka:
#client:
#serviceUrl:
#defaultZone: http://localhost:8761/eureka


#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/performance_service  # Correct database name
#    username: hbstudent                                      # MySQL username
#    password: hbstudent                               # MySQL password
#    driver-class-name: com.mysql.cj.jdbc.Driver           # MySQL driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update                                    # Automatically create/update tables
#    show-sql: true                                        # Show SQL queries in logs
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect       # MySQL-specific SQL dialect
#
#  profiles:
#    active: dev                                           # Activate the 'dev' profile (optional)


spring:
  application:
    name: performance-service
  datasource:
    username: hbstudent
    password: hbstudent
    url: jdbc:mysql://localhost:3306/performance_service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8085


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka