spring:
  application:
    name: recruitment-service
  datasource:
    username: hbstudent
    password: hbstudent
    url: jdbc:mysql://localhost:3306/recruitment_service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
